USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Exception on /webhooks/rest/webhook [POST]
Traceback (most recent call last):
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\joe\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\channels\channel.py", line 327, in receive
    on_new_message(UserMessage(text, collector, sender_id))
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\agent.py", line 305, in handle_message
    return processor.handle_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 77, in handle_message
    tracker = self.log_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 121, in log_message
    self._handle_message_with_tracker(message, tracker)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 241, in _handle_message_with_tracker
    parse_data = self._parse_message(message)
  File "C:\Users\joe\Anaconda3\lib\site-packages\rasa_core\processor.py", line 217, in _parse_message
    if (message.text.startswith(INTENT_MESSAGE_PREFIX) or
AttributeError: 'NoneType' object has no attribute 'startswith'
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
USING `rasa_core.server` is deprecated and will be removed in the future. Use `rasa_core.run --enable_api` instead.
Rasa process starting
Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
C:\Users\joe\Anaconda3\lib\site-packages\rasa_nlu\extractors\entity_synonyms.py:85: UserWarning: Failed to load synonyms file from 'models/nlu/default/weathernlu\entity_synonyms.json'
  "".format(entity_synonyms_file))

C:\Users\joe\Anaconda3\lib\site-packages\pykwalify\core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
